/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'meetingTranscription': MotiaStream<{ status: 'uploading' | 'transcribing' | 'processing' | 'completed' | 'failed'; progress: number; filename: string; duration?: number; transcript?: string; participants?: string[]; error?: string; summary?: string; actionItems?: string[]; keyTopics?: string[]; decisions?: string[]; sentimentAnalysis?: { overall: 'positive' | 'negative' | 'neutral'; confidence: number; positiveIndicators: number; negativeIndicators: number; energyLevel: 'high' | 'medium' | 'low' }; insights?: { participationScore: number; engagementLevel: 'high' | 'medium' | 'low'; meetingEfficiency: 'high' | 'medium' | 'low'; followUpNeeded: boolean; keyMetrics: { wordCount: number; estimatedSpeakingRate: number; participantCount: number } }; timestamp: string; localWhisperStatus?: string; whisperModel?: string; processingTime?: number }>
  }

  interface Handlers {
    'MeetingTranscriptionProcessor': EventHandler<{ filename: string; audioData?: string; language: string; model: string; transcriptionId: string; apiRequest?: boolean; localWhisperPath?: string }, never>
    'MeetingTranscriptionAPI': ApiRouteHandler<{ filename: string; audioData?: string; language?: string; model?: 'whisper-1' | 'whisper-large-v3'; localWhisperPath?: string }, ApiResponse<200, { message: string; traceId: string; transcriptionId: string; status: string; streamId: string; localWhisperPath?: string }> | ApiResponse<400, { error: string; details?: string }>, { topic: 'meeting-transcription'; data: { filename: string; audioData?: string; language: string; model: string; transcriptionId: string; apiRequest?: boolean; localWhisperPath?: string } }>
    'HelloWorld': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}